### PR TITLE
Feature/repeatables

### PR DESCRIPTION
**Pull request by ayush2k**
Continues #53  

Local branch had some merge issues.

`DCO 1.1 Signed-off-by: {{Ayush Gupta}} <{{ayush2k@gmail.com}}>`

### CODE REVIEW

**Comment by ayush2k** [comment]
@Snugug 

- Added server side rendering of repeatables
- Validation alert works fine now.

In order to completely work with Punchcard, we need to make changes in the punchcard.
Currently, rendering the form with errors after submit will not work. We need to format the `req.body` on submit in punchcard to make is work

**Comment by Snugug** [comment]
What happened to #53?

Can you please elaborate on the `req.body` part? If a change needs to be made, a story needs to be created for that and prioritized before I can bring this in. This also means this represents a breaking change, but I don't see any 💥 `:boom:` emoji to indicate that there is a breaking change somewhere

**Comment by ayush2k** [comment]
@Snugug 
I had a copy of content-types in the backup with server side rendering of repeatables but I already pushed the code for client side rendering.
Therefore, @scottnath suggested creating a new pull request instead of resolving all the changes.

Regarding, req.body change, I had a pull request for punchcard where instead of formatting the form data on retrieving the form, it formats the data into object with the values while saving it to the database. This we will not have to format it every time we get it from the database and also it makes the data more readable in the database itself. 
Now, I need to call that function again on post when the validation fails. I left it in the previous request. 
I can revert the change if this is not the correct way to do it.

**Comment by Snugug** [comment]
By creating a new pull request, all context and conversation of the previous pull request, _i.e._ the code review of the previous pull request, is gone. As it is no longer available, I now need to do code review over again on this PR, which will take even more time to do. If you would like to not update the previous PR and work here, that's fine, but then code review is going to start from the beginning again.

With the exception of a bug fix, if something worked previously and now does not, that is a breaking change. Breaking changes _are not bad_, but we need to be diligent about tracking our code and notifying our users of them. If this PR, as-is, can be used without modification of implementing code, great, it's a new feature. If implementing code needs to be modified to work with this new feature, that's fine as well, but it is also a breaking change.

**Comment by ayush2k** [comment]
@Snugug I will commit in the other PR. Hopefully will be up in 15-30 minutes

**Comment by Snugug** [comment]
Ok. I will close this then.

**Pull request closed without merging**
