### PR TITLE
:bug: new lodash was causing scripts bug

### PR DESCRIPTION
**Pull request by scottnath**
Fixes bug caused by lodash update.

---
Resolves #75

`DCO 1.1 Signed-off-by: Scott Nath <github@scottnath.com>`

### CODE REVIEW

**Comment by scottnath** [comment]
@Snugug here is the bug fix

**Comment by Snugug** [comment]
Please fix the bug caused by the update to lodash 4.14.1 in the [Greenkeeper branch](https://github.com/punchcard-cms/content-types/tree/greenkeeper-lodash-4.14.1) set up for the greenkeeper PR https://github.com/punchcard-cms/content-types/pull/75

**Comment by scottnath** [comment]
I'm confused Sam. This is the error from #75:
screen shot 2016-08-03 at 9 55 33 am

and here it is fixed in this build:
screen shot 2016-08-03 at 9 56 49 am


Can you please help me understand what is not fixed?

**Comment by Snugug** [comment]
I want you to fix it _there_. Greenkeeper creates branches when it updates dependencies, and the Lodash 4.14.1 update had the build break. As it's a braking change for something covered in our version range, it opens a PR to notify us of that. In this case, that branch, and that Greenkeeper PR, should be used to resolve that issue.

**Comment by scottnath** [comment]
tests waiting: https://github.com/punchcard-cms/content-types/pull/75

**Comment by Snugug** [comment]
Closed in favor of https://github.com/punchcard-cms/content-types/pull/75

**Pull request closed without merging**
